package com.mycompany.crsjava;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author huiyitew
 */
public class EligibilityUI extends javax.swing.JFrame {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EligibilityUI.class.getName());
    private final DefaultTableModel tableModel;
    
    private final UserManager um;
    private final User currentUser;
    
    public EligibilityUI(UserManager um, User currentUser) {
        this.um = um;
        this.currentUser = currentUser;
        initComponents();
        setLocationRelativeTo(null); // Center the screen
            
        tableModel = (DefaultTableModel) tblStudents.getModel();
        tableModel.setColumnIdentifiers(new Object[] {
            "ID", "Name", "CGPA", "Failed Courses", "Status"
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnCheckEligibility = new javax.swing.JButton();
        btnEnroll = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Eligibility Check");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        btnCheckEligibility.setText("Enroll Student");
        btnCheckEligibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckEligibilityActionPerformed(evt);
            }
        });

        btnEnroll.setText("Check Eligibility");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnEnroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnCheckEligibility)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckEligibility)
                    .addComponent(btnEnroll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckEligibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckEligibilityActionPerformed
int selectedRow = tblStudents.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a student from the list first.");
            return;
        }

        String status = tableModel.getValueAt(selectedRow, 4).toString();
        String studentName = tableModel.getValueAt(selectedRow, 1).toString();

        if (status.equals("Eligible")) {
            JOptionPane.showMessageDialog(this, 
                "Success! " + studentName + " has been enrolled for the next semester.");
        } else {
            JOptionPane.showMessageDialog(this, 
                "BLOCK: " + studentName + " cannot be enrolled.\nReason: Does not meet progression criteria.", 
                "Enrolment Error", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnCheckEligibilityActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
tableModel.setRowCount(0);

        List<Student> students = FileManager.loadAllData();

        for (Student s : students) {
            double cgpa = s.getCGPA();
            int failedCount = s.countFailedCourses(); // Ensure Student.java has this method
            
            boolean isEligible = (cgpa >= 2.0) && (failedCount <= 3);
            
            String status = isEligible ? "Eligible" : "Not Eligible";

            tableModel.addRow(new Object[] {
                s.getId(),
                s.getName(),
                String.format("%.2f", cgpa),
                failedCount,
                status
            });
        }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new AcademicOfficerMenu(um, currentUser).setVisible(true);    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckEligibility;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables
}
