package com.mycompany.crsjava;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author choks
 */
public class RecoveryPlanUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecoveryPlanUI.class.getName());
    
    private Student currentStudent;
    private RecoveryPlan currentPlan; 
    private final DefaultTableModel tableModel;
    private final UserManager um;
    private final User currentUser;
    
    public RecoveryPlanUI(UserManager um, User currentUser) {
        this.um = um;
        this.currentUser = currentUser;
        initComponents();
        
        tableModel = (DefaultTableModel) tblMilestones.getModel();
        tableModel.setColumnIdentifiers(new Object[]{"Week", "Task", "Status"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        cmbFailedCourses = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRecommendation = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMilestones = new javax.swing.JTable();
        btnAddMilestone = new javax.swing.JButton();
        btnRemoveMilestone = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnMarkCompleted = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("StudentID: ");

        btnLoad.setText("Find Student");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        cmbFailedCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFailedCoursesActionPerformed(evt);
            }
        });

        txtRecommendation.setColumns(20);
        txtRecommendation.setRows(5);
        jScrollPane1.setViewportView(txtRecommendation);

        jLabel2.setText("Recommendation: ");

        tblMilestones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblMilestones);

        btnAddMilestone.setText("Add Milestone");
        btnAddMilestone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMilestoneActionPerformed(evt);
            }
        });

        btnRemoveMilestone.setText("Remove Milestone");
        btnRemoveMilestone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveMilestoneActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnMarkCompleted.setText("Mark Complete");
        btnMarkCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkCompletedActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoad)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbFailedCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(244, 244, 244))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddMilestone, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnRemoveMilestone, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnMarkCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(btnSave))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFailedCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoad)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMilestone)
                    .addComponent(btnRemoveMilestone)
                    .addComponent(btnMarkCompleted))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
    String targetID = txtStudentID.getText().trim();
        List<Student> allStudents = FileManager.loadAllData();
        
        currentStudent = null;
        for(Student s : allStudents) {
            if(s.getId().equalsIgnoreCase(targetID)) {
                currentStudent = s;
                break;
            }
        }

        if(currentStudent == null) {
            JOptionPane.showMessageDialog(this, "Student not found!");
            return;
        }

        cmbFailedCourses.removeAllItems();
        List<Course> failedList = currentStudent.getFailedCourses(); // Uses method from Master Student class
        
        if(failedList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "This student has no failed courses!");
        } else {
            for(Course c : failedList) {
                cmbFailedCourses.addItem(c.getCode() + " - " + c.getLetterGrade());
            }
        }        
    }//GEN-LAST:event_btnLoadActionPerformed

    private void cmbFailedCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFailedCoursesActionPerformed
        if (currentStudent == null || cmbFailedCourses.getSelectedItem() == null) return;
        
        String selectedString = cmbFailedCourses.getSelectedItem().toString();
        String courseCode = selectedString.split(" - ")[0];

        RecoveryPlan loadedPlan = FileManager.loadPlan(currentStudent.getId(), courseCode);
        
        if (loadedPlan != null) {
            currentPlan = loadedPlan; // Use the existing plan
        } else {
            currentPlan = new RecoveryPlan(currentStudent.getId(), courseCode);
        }
        
        txtRecommendation.setText(currentPlan.getRecommendation());
        refreshTable();
    }//GEN-LAST:event_cmbFailedCoursesActionPerformed

    private void btnAddMilestoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMilestoneActionPerformed
if (currentPlan == null) {
            JOptionPane.showMessageDialog(this, "Please select a failed course first.");
            return;
        }
        
        String week = JOptionPane.showInputDialog("Enter Week (e.g., Week 1):");
        String task = JOptionPane.showInputDialog("Enter Task:");
        
        if (week != null && task != null) {
            currentPlan.addMilestone(week, task);
            refreshTable();
        }
    }//GEN-LAST:event_btnAddMilestoneActionPerformed

    private void btnRemoveMilestoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveMilestoneActionPerformed
       int selectedRow = tblMilestones.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a milestone in the table first.");
            return;
        }
        
        if (currentPlan != null) {
            currentPlan.removeMilestone(selectedRow);
            
            refreshTable(); 
        } 
    }//GEN-LAST:event_btnRemoveMilestoneActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (currentPlan != null) {
            currentPlan.setRecommendation(txtRecommendation.getText());
            
            FileManager.savePlan(currentPlan);
            
            JOptionPane.showMessageDialog(this, "Plan Saved Successfully to File!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnMarkCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkCompletedActionPerformed
        int selectedRow = tblMilestones.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a milestone to mark as complete.");
            return;
        }

        if (currentPlan != null) {
            RecoveryMilestone m = currentPlan.getMilestones().get(selectedRow);
            
            m.setStatus("Completed");
            
            refreshTable(); 
        }
    }//GEN-LAST:event_btnMarkCompletedActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new AcademicOfficerMenu(um, currentUser).setVisible(true);
        this.dispose();    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void refreshTable() {
        tableModel.setRowCount(0); // Clear table
        for (RecoveryMilestone m : currentPlan.getMilestones()) {
            tableModel.addRow(new Object[]{m.getWeek(), m.getTask(), m.getStatus()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMilestone;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnMarkCompleted;
    private javax.swing.JButton btnRemoveMilestone;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbFailedCourses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblMilestones;
    private javax.swing.JTextArea txtRecommendation;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
